### ISSUE TITLE
Did you get this working yet?

### ISSUE THREAD

**Issue by chrispsommers** [tklauser/filter2xdp#1]
Hi, I'm interested in the ability to convert a pcap filter expression into eBPF. Did you ever get this working, or are you aware of another effort to do this which is actually working? Thanks!

**Comment by tklauser** [comment]
Hi @chrispsommers. Thanks for your interest. Unfortunately I never got this working properly and currently lack the time to further work on it. I'm not aware of other efforts for something like this, but it might be worth asking on the xdp-newbies mailing list (http://vger.kernel.org/vger-lists.html#xdp-newbies).

**Comment by chrispsommers** [comment]
Tobias,
Many thanks for your response. Have a good day!

Regards,

Chris Sommers
